name: CI Pipeline

on:
  pull_request:
    branches: ["main", "cd-test"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build project
        run: ./scripts/build.sh

  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram (success)
        if: success()
        uses: appleboy/telegram-action@1b2bf60368dcf9d8375bd26bee6c94649f670968
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            New push to main branch!
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            "✅ CI passed for PR!"

      - name: Notify Telegram (failure)
        if: failure()
        uses: appleboy/telegram-action@1b2bf60368dcf9d8375bd26bee6c94649f670968
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            New push to main branch!
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            ❌ CI failed for PR!
